import type {
  ActuatorTest,
  CodingParameter,
  Dtc,
  EcuModule,
  PidDefinition,
  ServiceReset,
  VehicleProfile,
} from "./types";

export const DEMO_VEHICLE: VehicleProfile = {
  vin: "1HGCM82633A004352",
  year: 2019,
  make: "Ford",
  model: "Ranger 2.0 EcoBlue",
  engine: "2.0L I4 Turbo Diesel",
  protocol: "ISO 15765-4 CAN (11 bit / 500 kbaud)",
  odometerKm: 84210,
};

export const ECU_MODULES: EcuModule[] = [
  {
    id: "ecm",
    name: "Engine Control Module",
    abbr: "ECM",
    bus: "HS-CAN",
    address: "0x7E0",
    partNumber: "KB3A-12A650-BFC",
    softwareId: "SW 3.21.004",
    hardwareId: "HW C2",
    status: "unknown",
    x: 18,
    y: 22,
    dtcs: ["P0300", "P0401"],
  },
  {
    id: "tcm",
    name: "Transmission Control Module",
    abbr: "TCM",
    bus: "HS-CAN",
    address: "0x7E1",
    partNumber: "KB3P-7J115-AC",
    softwareId: "SW 1.08.11",
    hardwareId: "HW A4",
    status: "unknown",
    x: 42,
    y: 22,
    dtcs: [],
  },
  {
    id: "abs",
    name: "Anti-Lock Brake System",
    abbr: "ABS",
    bus: "HS-CAN",
    address: "0x760",
    partNumber: "JB3C-2C405-AE",
    softwareId: "SW 5.44.002",
    hardwareId: "HW B1",
    status: "unknown",
    x: 66,
    y: 22,
    dtcs: ["C0200"],
  },
  {
    id: "srs",
    name: "Supplemental Restraint System",
    abbr: "SRS",
    bus: "MS-CAN",
    address: "0x737",
    partNumber: "KB3T-14B321-AB",
    softwareId: "SW 2.10.000",
    hardwareId: "HW D0",
    status: "unknown",
    x: 18,
    y: 62,
    dtcs: [],
  },
  {
    id: "bcm",
    name: "Body Control Module",
    abbr: "BCM",
    bus: "MS-CAN",
    address: "0x726",
    partNumber: "KB3T-15604-DA",
    softwareId: "SW 8.02.017",
    hardwareId: "HW E3",
    status: "unknown",
    x: 42,
    y: 62,
    dtcs: ["U0100"],
  },
  {
    id: "eps",
    name: "Electric Power Steering",
    abbr: "EPS",
    bus: "HS-CAN",
    address: "0x730",
    partNumber: "KB3C-3D070-CB",
    softwareId: "SW 4.00.009",
    hardwareId: "HW A9",
    status: "unknown",
    x: 66,
    y: 62,
    dtcs: [],
  },
  {
    id: "ipc",
    name: "Instrument Panel Cluster",
    abbr: "IPC",
    bus: "MS-CAN",
    address: "0x720",
    partNumber: "KB3T-10849-AH",
    softwareId: "SW 6.30.114",
    hardwareId: "HW F1",
    status: "unknown",
    x: 88,
    y: 22,
    dtcs: [],
  },
  {
    id: "hvac",
    name: "Air Conditioning Control",
    abbr: "HVAC",
    bus: "LIN",
    address: "0x733",
    partNumber: "KB3T-19980-BB",
    softwareId: "SW 1.14.002",
    hardwareId: "HW B7",
    status: "unknown",
    x: 88,
    y: 62,
    dtcs: [],
  },
];

export const DTC_CATALOG: Dtc[] = [
  {
    code: "P0300",
    module: "ECM",
    description: "Random / Multiple Cylinder Misfire Detected",
    severity: "critical",
    state: "current",
    system: "Powertrain",
    occurrences: 12,
    causes: [
      "Worn or fouled injectors",
      "Low fuel rail pressure",
      "Intake manifold leak",
      "Failing glow plug circuit",
    ],
    freezeFrame: {
      rpm: 1840,
      speedKph: 46,
      coolantC: 88,
      loadPct: 62,
      fuelTrimShort: 6.2,
      fuelTrimLong: 11.7,
      intakeAirC: 34,
      mapKpa: 142,
      timingAdvance: 8.5,
      runtimeSec: 1245,
    },
  },
  {
    code: "P0401",
    module: "ECM",
    description: "Exhaust Gas Recirculation Flow Insufficient Detected",
    severity: "warning",
    state: "pending",
    system: "Powertrain",
    occurrences: 3,
    causes: ["Carboned EGR valve", "Blocked EGR cooler", "Faulty DPFE sensor"],
    freezeFrame: {
      rpm: 2210,
      speedKph: 72,
      coolantC: 91,
      loadPct: 48,
      fuelTrimShort: 2.1,
      fuelTrimLong: 4.4,
      intakeAirC: 31,
      mapKpa: 118,
      timingAdvance: 11,
      runtimeSec: 2870,
    },
  },
  {
    code: "C0200",
    module: "ABS",
    description: "Right Front Wheel Speed Sensor Circuit Malfunction",
    severity: "critical",
    state: "current",
    system: "Chassis",
    occurrences: 7,
    causes: [
      "Damaged sensor harness at knuckle",
      "Debris on tone ring",
      "Corroded connector C142",
    ],
    freezeFrame: {
      rpm: 1520,
      speedKph: 38,
      coolantC: 86,
      loadPct: 31,
      fuelTrimShort: 1.2,
      fuelTrimLong: 3.1,
      intakeAirC: 29,
      mapKpa: 101,
      timingAdvance: 9,
      runtimeSec: 640,
    },
  },
  {
    code: "U0100",
    module: "BCM",
    description: "Lost Communication With ECM/PCM 'A'",
    severity: "warning",
    state: "history",
    system: "Network",
    occurrences: 2,
    causes: ["Intermittent CAN bus termination", "Low system voltage event"],
  },
  {
    code: "B1318",
    module: "BCM",
    description: "Battery Voltage Low",
    severity: "info",
    state: "history",
    system: "Body",
    occurrences: 4,
    causes: ["Weak battery", "Charging system output low"],
  },
  {
    code: "P1450",
    module: "ECM",
    description: "Unable To Bleed Up Fuel Tank Vacuum (Manufacturer Specific)",
    severity: "info",
    state: "permanent",
    system: "Powertrain",
    occurrences: 1,
    causes: ["Restricted EVAP canister vent", "Blocked fuel tank vent line"],
  },
];

export const PIDS: PidDefinition[] = [
  { id: "rpm", pid: "010C", label: "Engine RPM", unit: "rpm", min: 0, max: 6000, group: "Engine" },
  { id: "speed", pid: "010D", label: "Vehicle Speed", unit: "km/h", min: 0, max: 220, group: "Chassis" },
  { id: "coolant", pid: "0105", label: "Coolant Temp", unit: "°C", min: -40, max: 130, group: "Engine" },
  { id: "load", pid: "0104", label: "Calculated Load", unit: "%", min: 0, max: 100, group: "Engine" },
  { id: "maf", pid: "0110", label: "MAF Air Flow", unit: "g/s", min: 0, max: 250, group: "Engine" },
  { id: "map", pid: "010B", label: "Intake MAP", unit: "kPa", min: 0, max: 255, group: "Engine" },
  { id: "o2", pid: "0114", label: "O2 Sensor B1S1", unit: "V", min: 0, max: 1.275, group: "Emissions" },
  { id: "stft", pid: "0106", label: "Short Fuel Trim B1", unit: "%", min: -100, max: 100, group: "Fuel" },
  { id: "ltft", pid: "0107", label: "Long Fuel Trim B1", unit: "%", min: -100, max: 100, group: "Fuel" },
  { id: "throttle", pid: "0111", label: "Throttle Position", unit: "%", min: 0, max: 100, group: "Engine" },
  { id: "intake", pid: "010F", label: "Intake Air Temp", unit: "°C", min: -40, max: 130, group: "Engine" },
  { id: "timing", pid: "010E", label: "Timing Advance", unit: "°", min: -64, max: 64, group: "Engine" },
  { id: "battery", pid: "0142", label: "Control Module Voltage", unit: "V", min: 0, max: 16, group: "Electrical" },
  { id: "fuelrail", pid: "0123", label: "Fuel Rail Pressure", unit: "bar", min: 0, max: 2000, group: "Fuel" },
];

export const ACTUATOR_TESTS: ActuatorTest[] = [
  {
    id: "fuel-pump",
    name: "Fuel Pump Relay",
    module: "ECM",
    description: "Energises the fuel pump relay and monitors rail pressure response.",
    kind: "toggle",
    durationMs: 6000,
    unit: "bar",
    warning: "Ensure the fuel system is not depressurised for service.",
  },
  {
    id: "injector-balance",
    name: "Injector Balance Test",
    module: "ECM",
    description: "Cuts each injector in sequence and records RPM drop per cylinder.",
    kind: "sweep",
    durationMs: 9000,
    unit: "rpm",
  },
  {
    id: "cooling-fan",
    name: "Cooling Fan Sweep",
    module: "ECM",
    description: "Ramps fan duty cycle from 0% to 100%.",
    kind: "sweep",
    durationMs: 7000,
    unit: "%",
  },
  {
    id: "abs-pump",
    name: "ABS Pump Motor & Valves",
    module: "ABS",
    description: "Cycles hydraulic modulator valves for brake bleeding.",
    kind: "pulse",
    durationMs: 8000,
    warning: "Keep hands clear of brake components. Pedal will move.",
  },
  {
    id: "egr-valve",
    name: "EGR Valve Actuation",
    module: "ECM",
    description: "Commands EGR position 0-100% and compares feedback.",
    kind: "sweep",
    durationMs: 6500,
    unit: "%",
  },
  {
    id: "hvac-blend",
    name: "HVAC Blend Door",
    module: "HVAC",
    description: "Drives blend door actuator full cold to full hot.",
    kind: "sweep",
    durationMs: 5000,
    unit: "%",
  },
  {
    id: "window-lift",
    name: "Window Lift Motors",
    module: "BCM",
    description: "Operates each door window motor in turn.",
    kind: "pulse",
    durationMs: 5000,
  },
  {
    id: "horn-lamps",
    name: "Horn & Exterior Lamps",
    module: "BCM",
    description: "Pulses horn relay and exterior lighting outputs.",
    kind: "pulse",
    durationMs: 4000,
    warning: "Loud. Warn bystanders before running.",
  },
];

export const SERVICE_RESETS: ServiceReset[] = [
  {
    id: "oil-reset",
    name: "Oil Service Reset",
    module: "IPC",
    description: "Resets the oil life counter and service interval distance.",
    steps: ["Verify ignition ON", "Request security access", "Write service counter", "Confirm cluster"],
    requiresIgnition: true,
  },
  {
    id: "epb",
    name: "Electronic Parking Brake Retract",
    module: "ABS",
    description: "Retracts rear calipers for brake pad replacement.",
    steps: ["Check battery > 12.4V", "Enter service mode", "Retract actuators", "Confirm retracted"],
    requiresIgnition: true,
  },
  {
    id: "dpf",
    name: "DPF Forced Regeneration",
    module: "ECM",
    description: "Runs a stationary diesel particulate filter burn-off cycle.",
    steps: ["Check soot load", "Raise idle to 2000 rpm", "Monitor EGT", "Complete regeneration"],
    requiresIgnition: true,
  },
  {
    id: "sas",
    name: "Steering Angle Sensor Calibration",
    module: "EPS",
    description: "Zeroes the steering angle sensor after alignment.",
    steps: ["Wheels straight ahead", "Clear stored angle", "Write zero point", "Verify 0.0°"],
    requiresIgnition: true,
  },
  {
    id: "tpms",
    name: "TPMS Sensor Relearn",
    module: "BCM",
    description: "Relearns tyre pressure sensor IDs to wheel positions.",
    steps: ["Enter relearn mode", "Trigger each sensor", "Store IDs", "Exit relearn"],
    requiresIgnition: true,
  },
  {
    id: "battery-reg",
    name: "Battery Registration",
    module: "BCM",
    description: "Registers a new battery with the charging strategy.",
    steps: ["Read current battery data", "Enter capacity & type", "Write registration", "Reset ageing counter"],
    requiresIgnition: false,
  },
  {
    id: "throttle-adapt",
    name: "Throttle Body Adaptation",
    module: "ECM",
    description: "Relearns throttle plate stop positions.",
    steps: ["Engine off, ignition on", "Clear adaptation", "Cycle throttle", "Store learned limits"],
    requiresIgnition: true,
  },
  {
    id: "injector-coding",
    name: "Injector Correction Coding",
    module: "ECM",
    description: "Writes IMA / injector correction codes per cylinder.",
    steps: ["Read current codes", "Enter new codes", "Write to ECM", "Verify readback"],
    requiresIgnition: true,
  },
];

export const CODING_PARAMETERS: CodingParameter[] = [
  {
    id: "seatbelt-chime",
    name: "Seatbelt Chime",
    module: "BCM",
    did: "0x2E 0xF1 0x90",
    options: ["Enabled", "Disabled"],
    value: "Enabled",
    note: "Disabling may be illegal for road use in some markets.",
  },
  {
    id: "drl",
    name: "Daytime Running Lights",
    module: "BCM",
    did: "0x2E 0xF1 0x91",
    options: ["Off", "Low Beam", "LED Strip", "Fog Lamps"],
    value: "LED Strip",
    note: "Controls DRL output source driver.",
  },
  {
    id: "auto-mirrors",
    name: "Auto-Fold Mirrors On Lock",
    module: "BCM",
    did: "0x2E 0xF1 0x94",
    options: ["Enabled", "Disabled"],
    value: "Disabled",
    note: "Requires powered folding mirror hardware.",
  },
  {
    id: "digital-speedo",
    name: "Digital Speedometer Unit",
    module: "IPC",
    did: "0x2E 0xF1 0xA2",
    options: ["km/h", "mph"],
    value: "km/h",
    note: "Changes cluster display unit and trip computer.",
  },
  {
    id: "lock-beep",
    name: "Lock Confirmation Beep",
    module: "BCM",
    did: "0x2E 0xF1 0x96",
    options: ["Enabled", "Disabled"],
    value: "Enabled",
    note: "Horn chirp on central locking.",
  },
  {
    id: "start-stop",
    name: "Auto Start-Stop Default",
    module: "ECM",
    did: "0x2E 0xF1 0x9B",
    options: ["On", "Off (memory)"],
    value: "On",
    note: "Sets the default state after each ignition cycle.",
  },
];

export const AT_COMMAND_HELP: { cmd: string; desc: string }[] = [
  { cmd: "AT Z", desc: "Reset the adapter" },
  { cmd: "AT I", desc: "Print adapter version" },
  { cmd: "AT E0", desc: "Echo off" },
  { cmd: "AT SP 6", desc: "Set protocol 6 (ISO 15765-4 CAN 11/500)" },
  { cmd: "AT DP", desc: "Describe current protocol" },
  { cmd: "AT RV", desc: "Read battery voltage" },
  { cmd: "01 0C", desc: "Mode 01 PID 0C — engine RPM" },
  { cmd: "03", desc: "Read stored diagnostic trouble codes" },
  { cmd: "22 11 01", desc: "UDS ReadDataByIdentifier 0x1101" },
];
