/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdaptersRouteImport } from './routes/adapters'
import { Route as CanbusRouteImport } from './routes/canbus'
import { Route as CodesRouteImport } from './routes/codes'
import { Route as ExpertRouteImport } from './routes/expert'
import { Route as FreezeFrameRouteImport } from './routes/freeze-frame'
import { Route as VehicleRouteImport } from './routes/vehicle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptersRoute = AdaptersRouteImport.update({
  id: '/adapters',
  path: '/adapters',
  getParentRoute: () => rootRouteImport,
} as any)
const CanbusRoute = CanbusRouteImport.update({
  id: '/canbus',
  path: '/canbus',
  getParentRoute: () => rootRouteImport,
} as any)
const CodesRoute = CodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertRoute = ExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => rootRouteImport,
} as any)
const FreezeFrameRoute = FreezeFrameRouteImport.update({
  id: '/freeze-frame',
  path: '/freeze-frame',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleRoute = VehicleRouteImport.update({
  id: '/vehicle',
  path: '/vehicle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/canbus': typeof CanbusRoute
  '/codes': typeof CodesRoute
  '/expert': typeof ExpertRoute
  '/freeze-frame': typeof FreezeFrameRoute
  '/vehicle': typeof VehicleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/canbus': typeof CanbusRoute
  '/codes': typeof CodesRoute
  '/expert': typeof ExpertRoute
  '/freeze-frame': typeof FreezeFrameRoute
  '/vehicle': typeof VehicleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/canbus': typeof CanbusRoute
  '/codes': typeof CodesRoute
  '/expert': typeof ExpertRoute
  '/freeze-frame': typeof FreezeFrameRoute
  '/vehicle': typeof VehicleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adapters'
    | '/canbus'
    | '/codes'
    | '/expert'
    | '/freeze-frame'
    | '/vehicle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adapters'
    | '/canbus'
    | '/codes'
    | '/expert'
    | '/freeze-frame'
    | '/vehicle'
  id:
    | '__root__'
    | '/'
    | '/adapters'
    | '/canbus'
    | '/codes'
    | '/expert'
    | '/freeze-frame'
    | '/vehicle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdaptersRoute: typeof AdaptersRoute
  CanbusRoute: typeof CanbusRoute
  CodesRoute: typeof CodesRoute
  ExpertRoute: typeof ExpertRoute
  FreezeFrameRoute: typeof FreezeFrameRoute
  VehicleRoute: typeof VehicleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adapters': {
      id: '/adapters'
      path: '/adapters'
      fullPath: '/adapters'
      preLoaderRoute: typeof AdaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canbus': {
      id: '/canbus'
      path: '/canbus'
      fullPath: '/canbus'
      preLoaderRoute: typeof CanbusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codes': {
      id: '/codes'
      path: '/codes'
      fullPath: '/codes'
      preLoaderRoute: typeof CodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert': {
      id: '/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof ExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freeze-frame': {
      id: '/freeze-frame'
      path: '/freeze-frame'
      fullPath: '/freeze-frame'
      preLoaderRoute: typeof FreezeFrameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle': {
      id: '/vehicle'
      path: '/vehicle'
      fullPath: '/vehicle'
      preLoaderRoute: typeof VehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdaptersRoute: AdaptersRoute,
  CanbusRoute: CanbusRoute,
  CodesRoute: CodesRoute,
  ExpertRoute: ExpertRoute,
  FreezeFrameRoute: FreezeFrameRoute,
  VehicleRoute: VehicleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
