/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodesRouteImport } from './routes/codes'
import { Route as FreezeFrameRouteImport } from './routes/freeze-frame'
import { Route as VehicleRouteImport } from './routes/vehicle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodesRoute = CodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => rootRouteImport,
} as any)
const FreezeFrameRoute = FreezeFrameRouteImport.update({
  id: '/freeze-frame',
  path: '/freeze-frame',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleRoute = VehicleRouteImport.update({
  id: '/vehicle',
  path: '/vehicle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/codes': typeof CodesRoute
  '/freeze-frame': typeof FreezeFrameRoute
  '/vehicle': typeof VehicleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/codes': typeof CodesRoute
  '/freeze-frame': typeof FreezeFrameRoute
  '/vehicle': typeof VehicleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/codes': typeof CodesRoute
  '/freeze-frame': typeof FreezeFrameRoute
  '/vehicle': typeof VehicleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/codes' | '/freeze-frame' | '/vehicle'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/codes' | '/freeze-frame' | '/vehicle'
  id: '__root__' | '/' | '/codes' | '/freeze-frame' | '/vehicle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodesRoute: typeof CodesRoute
  FreezeFrameRoute: typeof FreezeFrameRoute
  VehicleRoute: typeof VehicleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codes': {
      id: '/codes'
      path: '/codes'
      fullPath: '/codes'
      preLoaderRoute: typeof CodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freeze-frame': {
      id: '/freeze-frame'
      path: '/freeze-frame'
      fullPath: '/freeze-frame'
      preLoaderRoute: typeof FreezeFrameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle': {
      id: '/vehicle'
      path: '/vehicle'
      fullPath: '/vehicle'
      preLoaderRoute: typeof VehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodesRoute: CodesRoute,
  FreezeFrameRoute: FreezeFrameRoute,
  VehicleRoute: VehicleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
